# Generated by Django 3.0.7 on 2020-07-30 09:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
