version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      #      - python/load-cache
      #      - python/install-deps
      #      - python/save-cache
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          command: |
            cd src/
            python manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
