version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3 # Invoke the Heroku orb

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.7.4
      - image: circleci/mariadb:10.1.44
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          MYSQL_USER: django
          MYSQL_PASSWORD: SmartMariaScribbleDB2000!
          MYSQL_DATABASE: test_smartscribbledb
    steps:
      - checkout
      - restore_cache:
          keys:
            - -pypi-v1-{{ .Branch }}-{{ checksum "~/project/requirements.txt" }}-{{ checksum "/home/circleci/.pyenv/version" }}-
      - run:
          command: "pip install -r requirements.txt \n"
          name: Install dependencies with pip using project requirements.txt
          working_directory: ~/project
      - save_cache:
          key: -pypi-v1-{{ .Branch }}-{{ checksum "~/project/requirements.txt" }}-{{ checksum "/home/circleci/.pyenv/version" }}-
          paths:
            - /home/circleci/.cache/pip
            - /home/circleci/.pyenv/versions/
            - /home/circleci/.local/lib/
      - run:
          name: Install MySQL CLI; grant user privileges
          command: |
            sudo apt update
            sudo apt install mariadb-client
            echo "Deleting database"
            mariadb -h 127.0.0.1 -u django --password=SmartMariaScribbleDB2000! --execute="DROP DATABASE test_smartscribbledb"
      - run:
          command: |
            cd src/
            python manage.py collectstatic --noinput
            python manage.py test
          name: Test

workflows:
  heroku_deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build-and-test
          filters:
            branches:
              only: master