# Generated by Django 3.0.7 on 2020-09-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200921_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='prediction_model',
            field=models.CharField(choices=[('gpt-2', 'Gpt2'), ('bert', 'Bert'), ('albert', 'Albert')], default='GPT2', max_length=6),
        ),
    ]
