# Generated by Django 3.0.7 on 2021-01-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20201016_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='prediction_model',
            field=models.CharField(choices=[('gpt-2', 'Gpt2'), ('bert', 'Bert'), ('albert', 'Albert'), ('distil-gpt2', 'Dgpt2'), ('bert-sp', 'Bertsp')], default='GPT2', max_length=15),
        ),
    ]
