#!/bin/bash

APPNAME="SmartScribble"
FILEPATH="$(dirname "$(readlink -f "$0")")"
DJANGODIR="$FILEPATH/$APPNAME"
SOCKFILE="$FILEPATH/run/gunicorn.sock"
NUM_WORKERS=1
DJANGO_SETTINGS_MODULE="$APPNAME.settings"
DJANGO_WSGI_MODULE="$APPNAME.wsgi"
TIMEOUT=120
echo "Starting $NAME as `whoami`"
# Activate the virtual environment
echo $DJANGODIR
cd $FILEPATH
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR


exec gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $APPNAME \
--workers $NUM_WORKERS \
--timeout $TIMEOUT \
--bind=unix:$SOCKFILE \
--log-level=debug \
--log-file=-


